name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature are you suggesting?
      options:
        - New Analysis Method
        - Visualization Enhancement
        - Documentation Improvement
        - Code Quality / Testing
        - Performance Optimization
        - New Empirical Test
        - Theoretical Extension
        - Infrastructure / Tooling
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? What problem does it solve?
      placeholder: I'm frustrated when... / It would be useful to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I propose adding...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered alternative solutions or approaches?
      placeholder: I also considered...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature benefit the project and community?
      placeholder: This would help by...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how to implement this, share them here
      placeholder: This could be implemented by...

  - type: dropdown
    id: contribution
    attributes:
      label: Willing to Contribute?
      description: Would you be willing to help implement this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance"
        - "No, just suggesting"
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the [CONTRIBUTING.md](https://github.com/AshmanRoonz/Fractal_Reality/blob/main/CONTRIBUTING.md)
          required: true
        - label: This aligns with the project's goals and scope
          required: false
